CREATE TABLE vape_shop_products (
    product_name VARCHAR(50),
    price DECIMAL(5,2),
    puffs INT,
    color VARCHAR(20),
    electric BOOLEAN,
    flavor VARCHAR(30),
    image_link VARCHAR(100)
);

-- Insert data into the vape_shop_products table
INSERT INTO vape_shop_products (product_name, price, puffs, color, electric, flavor, image_link)
VALUES
('VapeX Pro', 30.99, 700, 'Black', TRUE, 'Mint', 'https://source.roboflow.com/fkgYVbpsPkStaRnG33gHyl0WenM2/nuv0QEl4jnDJPBk86wMK/annotation-Vape.png?v=2024-07-22T20:16:20.651Z'),
('CloudChaser Max', 25.99, 600, 'Red', TRUE, 'Strawberry', 'http://example.com/image2.jpg'),
('PuffMaster 3000', 30.00, 700, 'Blue', TRUE, 'Blueberry', 'http://example.com/image3.jpg'),
('EcoSmoke Mini', 15.49, 350, 'Green', TRUE, 'Watermelon', 'http://example.com/image4.jpg'),
('TurboVape Xtreme', 40.00, 800, 'Black', TRUE, 'Grape', 'http://example.com/image5.jpg'),
('CloudKing S', 22.99, 500, 'Silver', TRUE, 'Mango', 'http://example.com/image6.jpg'),
('VaporFlex', 35.99, 700, 'Yellow', TRUE, 'Banana', 'http://example.com/image7.jpg'),
('SmoothVape', 20.00, 400, 'Pink', TRUE, 'Pineapple', 'http://example.com/image8.jpg'),
('CoolMist Pro', 18.00, 450, 'Purple', TRUE, 'Mint', 'http://example.com/image9.jpg'),
('ZenPuff', 26.99, 600, 'White', TRUE, 'Cherry', 'http://example.com/image10.jpg'),
('VapeWind', 17.50, 300, 'Gray', TRUE, 'Apple', 'http://example.com/image11.jpg'),
('FirePuff Max', 28.99, 750, 'Red', TRUE, 'Lemon', 'http://example.com/image12.jpg'),
('AeroVape', 34.99, 650, 'Black', TRUE, 'Peach', 'http://example.com/image13.jpg'),
('FreshAir Mini', 14.99, 300, 'Green', FALSE, 'Lime', 'http://example.com/image14.jpg'),
('StormCloud', 21.99, 500, 'Blue', TRUE, 'Guava', 'http://example.com/image15.jpg'),
('VaporCloud Ultra', 29.99, 750, 'Purple', TRUE, 'Raspberry', 'http://example.com/image16.jpg'),
('CloudBurst', 19.50, 400, 'White', TRUE, 'Cola', 'http://example.com/image17.jpg'),
('BreezeVape S', 27.99, 650, 'Silver', TRUE, 'Orange', 'http://example.com/image18.jpg'),
('PurePuff Lite', 23.00, 550, 'Pink', TRUE, 'Grapefruit', 'http://example.com/image19.jpg'),
('TurboMist', 32.99, 800, 'Yellow', TRUE, 'Passionfruit', 'http://example.com/image20.jpg'),
('FreshVape Max', 24.50, 600, 'Red', TRUE, 'Melon', 'http://example.com/image21.jpg'),
('VapeMaster', 39.00, 850, 'Blue', TRUE, 'Berry', 'http://example.com/image22.jpg'),
('CloudFlex', 37.50, 700, 'Black', TRUE, 'Pineapple', 'http://example.com/image23.jpg'),
('VaporZest', 26.99, 500, 'Green', TRUE, 'Mint', 'http://example.com/image24.jpg'),
('WindPuff', 20.00, 450, 'Gray', FALSE, 'Lemon', 'http://example.com/image25.jpg'),
('TurboPuff', 31.50, 750, 'Purple', TRUE, 'Mango', 'http://example.com/image26.jpg'),
('CloudRush', 19.99, 400, 'White', TRUE, 'Banana', 'http://example.com/image27.jpg'),
('BreezeMist', 22.50, 550, 'Silver', TRUE, 'Peach', 'http://example.com/image28.jpg'),
('VapeSmooth', 29.99, 600, 'Black', TRUE, 'Strawberry', 'http://example.com/image29.jpg'),
('SkyMist', 33.50, 700, 'Blue', TRUE, 'Blueberry', 'http://example.com/image30.jpg'),
('FreshMist', 16.50, 300, 'Green', FALSE, 'Apple', 'http://example.com/image31.jpg'),
('StormChaser', 28.00, 750, 'Red', TRUE, 'Watermelon', 'http://example.com/image32.jpg'),
('AeroPuff', 34.00, 650, 'Yellow', TRUE, 'Grape', 'http://example.com/image33.jpg'),
('ZenVape', 21.00, 500, 'Pink', TRUE, 'Pineapple', 'http://example.com/image34.jpg'),
('PureVape Lite', 24.99, 550, 'Purple', TRUE, 'Mint', 'http://example.com/image35.jpg'),
('EcoCloud', 18.99, 400, 'White', FALSE, 'Cherry', 'http://example.com/image36.jpg'),
('TurboAir', 30.50, 700, 'Silver', TRUE, 'Mango', 'http://example.com/image37.jpg'),
('VapeRush', 19.00, 350, 'Red', TRUE, 'Grapefruit', 'http://example.com/image38.jpg'),
('BreezeMax', 25.99, 600, 'Gray', TRUE, 'Cola', 'http://example.com/image39.jpg'),
('CoolMist X', 17.99, 400, 'Green', FALSE, 'Lime', 'http://example.com/image40.jpg'),
('VaporFlex Pro', 36.50, 750, 'Black', TRUE, 'Guava', 'http://example.com/image41.jpg'),
('StormVape', 22.00, 500, 'Blue', TRUE, 'Raspberry', 'http://example.com/image42.jpg'),
('CloudPro', 32.00, 650, 'Purple', TRUE, 'Apple', 'http://example.com/image43.jpg'),
('SkyVape', 27.99, 550, 'Yellow', TRUE, 'Orange', 'http://example.com/image44.jpg'),
('WindFlex', 35.99, 700, 'Pink', TRUE, 'Passionfruit', 'http://example.com/image45.jpg'),
('VaporMax', 23.99, 600, 'Silver', TRUE, 'Berry', 'http://example.com/image46.jpg'),
('CloudMist Lite', 16.00, 300, 'Black', FALSE, 'Peach', 'http://example.com/image47.jpg'),
('TurboVape Pro', 39.99, 850, 'Red', TRUE, 'Strawberry', 'http://example.com/image48.jpg'),
('ZenCloud', 19.99, 450, 'Blue', TRUE, 'Blueberry', 'http://example.com/image49.jpg'),
('PuffMaster Max', 28.00, 700, 'Green', TRUE, 'Watermelon', 'http://example.com/image50.jpg');
